workflows:
    boring-workflow:
        name: Boring Pipeline
        scripts:
          - name: CICD Started
            script: echo "Welcome to your CICD set up"
          - name: Build Boring app
            script: |
              xcode-project build-ipa \
                --workspace "CentralDoApito/BoringDay/BoringDay.xcodeproj/project.xcworkspace" \
                --scheme "CentralDoApito/BoringDay/BoringDay"
          - name: iOS test
            script: |
              xcode-project run-tests \
                --workspace CentralDoApito/BoringDay/BoringDay.xcodeproj/project.xcworkspace\
                --scheme BoringDay
        publishing:
          email:
            recipients:
              - gabriel.felipo2010@gmail.com
            notify:
              success: true
              failure: true

